package irc

import (
	"log"
)

func init() {
	log.SetFlags(log.Lshortfile)
}

// Reply codes:
const (
	// Replies in the range from 001 to 099 are used for client-server connections only and should never travel between servers.
	ircRplWELCOME  = "1" // "Welcome to the Internet Relay Network <nick>!<user>@<host>"
	ircRplYOURHOST = "2" // "Your host is <servername>, running version <ver>"
	ircRplCREATED  = "3" // "This server was created <date>"
	ircRplMYINFO   = "4" // "<servername> <version> <available user modes> <available channel modes>"
	ircRplBOUNCE   = "5" // "Try server <server name>, port <port number>"

	// Replies generated in the response to commands are found in the range from 200 to 399.
	ircRplTRACELINK       = "200" // "Link <version & debug level> <destination> <next server> V<protocol version> <link uptime in seconds> <backstream sendq> <upstream sendq>"
	ircRplTRACECONNECTING = "201" // "Try. <class> <server>"
	ircRplTRACEHANDSHAKE  = "202" // "H.S. <class> <server>"
	ircRplTRACEUNKNOWN    = "203" // "???? <class> [<client IP address in dot form>]"
	ircRplTRACEOPERATOR   = "204" // "Oper <class> <nick>"
	ircRplTRACEUSER       = "205" // "User <class> <nick>"
	ircRplTRACESERVER     = "206" // "Serv <class> <int>S <int>C <server> <nick!user|*!*>@<host|server> V<protocol version>"
	ircRplTRACESERVICE    = "207" // "Service <class> <name> <type> <active type>"
	ircRplTRACENEWTYPE    = "208" // "<newtype> 0 <client name>"
	ircRplTRACECLASS      = "209" // "Class <class> <count>"
	ircRplTRACERECONNECT  = "210" // Unused.
	ircRplSTATSLINKINFO   = "211" // "<linkname> <sendq> <sent messages> <sent Kbytes> <received messages> <received Kbytes> <time open>"
	ircRplSTATSCOMMANDS   = "212" // "<command> <count> <byte count> <remote count>"
	ircRplENDOFSTATS      = "219" // "<stats letter> :End of STATS report"
	ircRplUMODEIS         = "221" // "<user mode string>"
	ircRplSERVLIST        = "234" // "<name> <server> <mask> <type> <hopcount> <info>"
	ircRplSERVLISTEND     = "235" // "<mask> <type> :End of service listing"
	ircRplSTATSUPTIME     = "242" // ":Server Up %d days %d:%02d:%02d"
	ircRplSTATSOLINE      = "243" // "O <hostmask> * <name>"
	ircRplLUSERCLIENT     = "251" // ":There are <integer> users and <integer> services on <integer> servers"
	ircRplLUSEROP         = "252" // "<integer> :operator(s) online"
	ircRplLUSERUNKNOWN    = "253" // "<integer> :unknown connection(s)"
	ircRplLUSERCHANNELS   = "254" // "<integer> :channels formed"
	ircRplLUSERME         = "255" // ":I have <integer> clients and <integer> servers"
	ircRplADMINME         = "256" // "<server> :Administrative info"
	ircRplADMINLOC1       = "257" // ":<admin info>"
	ircRplADMINLOC2       = "258" // ":<admin info>"
	ircRplADMINEMAIL      = "259" // ":<admin info>"
	ircRplTRACELOG        = "261" // "File <logfile> <debug level>"
	ircRplTRACEEND        = "262" // "<server name> <version & debug level> :End of TRACE"
	ircRplTRYAGAIN        = "263" // "<command> :Please wait a while and try again."
	ircRplAWAY            = "301" // "<nick> :<away message>"
	ircRplUSERHOST        = "302" // ":*1<reply> *( " " <reply> )"
	ircRplISON            = "303" // ":*1<nick> *( " " <nick> )"
	ircRplUNAWAY          = "305" // ":You are no longer marked as being away"
	ircRplNOWAWAY         = "306" // ":You have been marked as being away"
	ircRplWHOISUSER       = "311" // "<nick> <user> <host> * :<real name>"
	ircRplWHOISSERVER     = "312" // "<nick> <server> :<server info>"
	ircRplWHOISOPERATOR   = "313" // "<nick> :is an IRC operator"
	ircRplWHOWASUSER      = "314" // "<nick> <user> <host> * :<real name>"
	ircRplENDOFWHO        = "315" // "<name> :End of WHO list"
	ircRplWHOISIDLE       = "317" // "<nick> <integer> :seconds idle"
	ircRplENDOFWHOIS      = "318" // "<nick> :End of WHOIS list"
	ircRplWHOISCHANNELS   = "319" // "<nick> :*( ( "@" / "+" ) <channel> " " )"
	ircRplLISTSTART       = "321" // Obsolete.
	ircRplLIST            = "322" // "<channel> <# visible> :<topic>"
	ircRplLISTEND         = "323" // ":End of LIST"
	ircRplCHANNELMODEIS   = "324" // "<channel> <mode> <mode params>"
	ircRplUNIQOPIS        = "325" // "<channel> <nickname>"
	ircRplNOTOPIC         = "331" // "<channel> :No topic is set"
	ircRplTOPIC           = "332" // "<channel> :<topic>"
	ircRplINVITING        = "341" // "<channel> <nick>"
	ircRplSUMMONING       = "342" // "<user> :Summoning user to IRC"
	ircRplINVITELIST      = "346" // "<channel> <invitemask>"
	ircRplENDOFINVITELIST = "347" // "<channel> :End of channel invite list"
	ircRplEXCEPTLIST      = "348" // "<channel> <exceptionmask>"
	ircRplENDOFEXCEPTLIST = "349" // "<channel> :End of channel exception list"
	ircRplVERSION         = "351" // "<version>.<debuglevel> <server> :<comments>"
	ircRplWHOREPLY        = "352" // "<channel> <user> <host> <server> <nick> ( "H" / "G" > ["*"] [ ( "@" / "+" ) ] :<hopcount> <real name>"
	ircRplNAMREPLY        = "353" // "( "=" / "*" / "@" ) <channel> :[ "@" / "+" ] <nick> *( " " [ "@" / "+" ] <nick> )"
	ircRplLINKS           = "364" // "<mask> <server> :<hopcount> <server info>"
	ircRplENDOFLINKS      = "365" // "<mask> :End of LINKS list"
	ircRplENDOFNAMES      = "366" // "<channel> :End of NAMES list"
	ircRplBANLIST         = "367" // "<channel> <banmask>"
	ircRplENDOFBANLIST    = "368" // "<channel> :End of channel ban list"
	ircRplENDOFWHOWAS     = "369" // "<nick> :End of WHOWAS"
	ircRplINFO            = "371" // ":<string>"
	ircRplMOTD            = "372" // ":- <text>"
	ircRplENDOFINFO       = "374" // ":End of INFO list"
	ircRplMOTDSTART       = "375" // ":- <server> Message of the day - "
	ircRplENDOFMOTD       = "376" // ":End of MOTD command"
	ircRplYOUREOPER       = "381" // ":You are now an IRC operator"
	ircRplREHASHING       = "382" // "<config file> :Rehashing"
	ircRplYOURESERVICE    = "383" // "You are service <servicename>"
	ircRplTIME            = "391" // "<server> :<string showing server's local time>"
	ircRplUSERSSTART      = "392" // ":UserID Terminal Host"
	ircRplUSERS           = "393" // ":<username> <ttyline> <hostname>"
	ircRplENDOFUSERS      = "394" // ":End of users"
	ircRplNOUSERS         = "395" // ":Nobody logged in"

	//Error replies are found in the range from 400 to 599.
	ircErrNOSUCHNICK        = "401" // "<nickname> :No such nick/channel"
	ircErrNOSUCHSERVER      = "402" // "<server name> :No such server"
	ircErrNOSUCHCHANNEL     = "403" // "<channel name> :No such channel"
	ircErrCANNOTSENDTOCHAN  = "404" // "<channel name> :Cannot send to channel"
	ircErrTOOMANYCHANNELS   = "405" // "<channel name> :You have joined too many channels"
	ircErrWASNOSUCHNICK     = "406" // "<nickname> :There was no such nickname"
	ircErrTOOMANYTARGETS    = "407" // "<target> :<error code> recipients. <abort message>"
	ircErrNOSUCHSERVICE     = "408" // "<service name> :No such service"
	ircErrNOORIGIN          = "409" // ":No origin specified"
	ircErrNORECIPIENT       = "411" // ":No recipient given (<command>)"
	ircErrNOTEXTTOSEND      = "412" // ":No text to send"
	ircErrNOTOPLEVEL        = "413" // "<mask> :No toplevel domain specified"
	ircErrWILDTOPLEVEL      = "414" // "<mask> :Wildcard in toplevel domain"
	ircErrBADMASK           = "415" // "<mask> :Bad Server/host mask"
	ircErrUNKNOWNCOMMAND    = "421" // "<command> :Unknown command"
	ircErrNOMOTD            = "422" // ":MOTD File is missing"
	ircErrNOADMININFO       = "423" // "<server> :No administrative info available"
	ircErrFILEERROR         = "424" // ":File error doing <file op> on <file>"
	ircErrNONICKNAMEGIVEN   = "431" // ":No nickname given"
	ircErrERRONEUSNICKNAME  = "432" // "<nick> :Erroneous nickname"
	ircErrNICKNAMEINUSE     = "433" // "<nick> :Nickname is already in use"
	ircErrNICKCOLLISION     = "436" // "<nick> :Nickname collision KILL from <user>@<host>"
	ircErrUNAVAILRESOURCE   = "437" // "<nick/channel> :Nick/channel is temporarily unavailable"
	ircErrUSERNOTINCHANNEL  = "441" // "<nick> <channel> :They aren't on that channel"
	ircErrNOTONCHANNEL      = "442" // "<channel> :You're not on that channel"
	ircErrUSERONCHANNEL     = "443" // "<user> <channel> :is already on channel"
	ircErrNOLOGIN           = "444" // "<user> :User not logged in"
	ircErrSUMMONDISABLED    = "445" // ":SUMMON has been disabled"
	ircErrUSERSDISABLED     = "446" // ":USERS has been disabled"
	ircErrNOTREGISTERED     = "451" // ":You have not registered"
	ircErrNEEDMOREPARAMS    = "461" // "<command> :Not enough parameters"
	ircErrALREADYREGISTRED  = "462" // ":Unauthorized command (already registered)"
	ircErrNOPERMFORHOST     = "463" // ":Your host isn't among the privileged"
	ircErrPASSWDMISMATCH    = "464" // ":Password incorrect"
	ircErrYOUREBANNEDCREEP  = "465" // ":You are banned from this server"
	ircErrYOUWILLBEBANNED   = "466" //
	ircErrKEYSET            = "467" // "<channel> :Channel key already set"
	ircErrCHANNELISFULL     = "471" // "<channel> :Cannot join channel (+l)"
	ircErrUNKNOWNMODE       = "472" // "<char> :is unknown mode char to me for <channel>"
	ircErrINVITEONLYCHAN    = "473" // "<channel> :Cannot join channel (+i)"
	ircErrBANNEDFROMCHAN    = "474" // "<channel> :Cannot join channel (+b)"
	ircErrBADCHANNELKEY     = "475" // "<channel> :Cannot join channel (+k)"
	ircErrBADCHANMASK       = "476" // "<channel> :Bad Channel Mask"
	ircErrNOCHANMODES       = "477" // "<channel> :Channel doesn't support modes"
	ircErrBANLISTFULL       = "478" // "<channel> <char> :Channel list is full"
	ircErrNOPRIVILEGES      = "481" // ":Permission Denied- You're not an IRC operator"
	ircErrCHANOPRIVSNEEDED  = "482" // "<channel> :You're not channel operator"
	ircErrCANTKILLSERVER    = "483" // ":You can't kill a server!"
	ircErrRESTRICTED        = "484" // ":Your connection is restricted!"
	ircErrUNIQOPPRIVSNEEDED = "485" // ":You're not the original channel operator"
	ircErrNOOPERHOST        = "491" // ":No O-lines for your host"
	ircErrUMODEUNKNOWNFLAG  = "501" // ":Unknown MODE flag"
	ircErrUSERSDONTMATCH    = "502" // ":Cannot change mode for other users"
)
